lab-2(30.03)
is-tech-y24-2/Danchechek pull request #2
Opened 2022-03-29 23:04 UTC by Danchechek

2022-04-02 10:27 UTC, Arthasasyan requested changes
target удалить
pom'ов не хватает

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/Service.iml
> +<?xml version="1.0" encoding="UTF-8"?>
iml файлы удалить

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/Service.iml
> +<?xml version="1.0" encoding="UTF-8"?>
kotiki-java

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/pom.xml
> +        <groupId>ru.itmo</groupId>
Имя проекта https://maven.apache.org/guides/mini/guide-naming-conventions.html

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/pom.xml
> +            <version>1.0-SNAPSHOT</version>
В проперти

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/pom.xml
> +            <version>1.0-SNAPSHOT</version>
https://maven.apache.org/pom.html#properties

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/src/main/java/Service.java
> +public class Service {
1. Разные сервисы

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/src/main/java/Service.java
> +public class Service {
2. Интерфейсы

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/src/main/java/tools/BanksException.java
> +    BanksException() {
без public?

2022-04-02 10:27 UTC, Arthasasyan commented on kote/Service/src/main/java/tools/BanksException.java
> +package tools;
Пакеты

2022-04-02 10:27 UTC, Arthasasyan commented on kote/src/main/java/dao/CatDAO.java
> +    public Cat findById(int id);
public

2022-04-02 10:27 UTC, Arthasasyan commented on kote/src/main/java/models/Cat.java
> +@Table(name = "cats3")
3?

2022-04-02 10:27 UTC, Arthasasyan commented on kote/src/main/java/models/Cat.java
> +    private String color;
enum

2022-04-02 10:27 UTC, Arthasasyan commented on kote/src/main/java/models/Cat.java
> +//    public void addFriend(String id)
Артефакты разработки

2022-04-13 20:18 UTC, Arthasasyan requested changes
target папки нужно удалить

2022-04-13 20:18 UTC, Arthasasyan commented on kote/Service/pom.xml
> +        <groupId>ru.itmo</groupId>
Не исправлено

2022-04-13 20:18 UTC, Arthasasyan commented on kote/Service/pom.xml
> +    <artifactId>Service</artifactId>
Артефакты называются в kebab-case

2022-04-13 20:18 UTC, Arthasasyan commented on kote/Service/src/main/java/Main.java
> +import enums.EnumBD;
Пакеты

2022-04-13 20:18 UTC, Arthasasyan commented on kote/Service/src/main/java/service/solution/CatServiceImpl.java
> +                .filter(i -> catDAO.getAll().get(i).getPassportCode() == cat.getPassportCode())
Так, ну это че-то перебор
Есть обычная операция insert/update

2022-04-13 20:18 UTC, Arthasasyan commented on kote/Service/src/main/java/service/solution/CatServiceImpl.java
> +            if ((getAllFriends().get(i).getSecond() == friends.getSecond()
getAllFriends -- сложная операция, ее нужно закешировать

2022-04-13 20:18 UTC, Arthasasyan commented on kote/Service/src/test/java/ServiceTest.java
> +import models.Cat;
Папка должна называться kotiki-java, это принципиально для инфраструктуры

2022-04-13 20:18 UTC, Arthasasyan commented on kote/src/main/java/dao/solution/CatDAOImpl.java
> +            if(getAll().get(i).getPassportOwner() == cat.getPassportOwner()
getAll.get явно можно упростить до одного селекта (да и вообще это зафиксировать)

2022-04-13 20:18 UTC, Arthasasyan commented on kote/src/main/java/models/Cat.java
> +    private String color;
Не исправлено

2022-04-16 10:45 UTC, Arthasasyan requested changes

2022-04-16 10:45 UTC, Arthasasyan commented on kote-java/Service/src/main/java/service/CatService.java
> +package service;
Пакеты

2022-04-16 10:45 UTC, Arthasasyan commented on kote-java/Service/pom.xml
> +            <groupId>ru.itmo</groupId>
Группа

2022-04-16 10:45 UTC, Arthasasyan commented on kote-java/Service/src/main/java/service/solution/CatServiceImpl.java
> +            if (ownerDAO.getAll().get(i).getPassportCode() == cat.getPassportOwner()) {
getAll

2022-04-16 10:45 UTC, Arthasasyan commented on kote-java/src/main/java/dao/CatDAO.java
> +package dao;
kotiki-java

2022-04-16 10:45 UTC, Arthasasyan commented on kote-java/src/main/java/dao/solution/OwnerDAOImpl.java
> +            System.out.println(getAll().get(i).getName());
Библиотеки для логов

2022-04-16 11:09 UTC, Arthasasyan requested changes

2022-04-16 11:09 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/service/interfaces/CatService.java
> +package service.interfaces;
Пакеты

2022-04-16 11:09 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/service/solution/CatServiceImpl.java
> +        var all = ownerDAO.getAll();
Не нужно

2022-04-16 11:09 UTC, Arthasasyan commented on kotiki-java/src/main/java/dao/solution/OwnerDAOImpl.java
> +            System.out.println(getAll().get(i).getName());
Логи

2022-04-16 11:45 UTC, Arthasasyan requested changes

2022-04-16 11:45 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/Main.java
> +public class Main {
В пакет

2022-04-16 11:45 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/service/interfaces/CatService.java
> +    ArrayList<Cat> getFriendsCat(int passportCode);
Интерфейсы

2022-04-16 11:45 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/service/solution/CatServiceImpl.java
> +        {
Реформат кода

2022-04-16 11:45 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/service/solution/CatServiceImpl.java
> +        var all = catDAO.getAll();
getAll

2022-05-11 19:48 UTC, Arthasasyan requested changes

2022-05-11 19:48 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/Main.java
> +public class Main {
Физически тоже нужно вынести в папку

2022-05-11 19:48 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/service/solution/CatServiceImpl.java
> +        List<Friends> allPairs = friendsDAO.getAll();
Фильтрацию нужно вынести на уровень БД

2022-05-11 19:48 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/service/solution/CatServiceImpl.java
> +        List<Friends> allPairs = friendsDAO.getAll();
getAll в принципе должен остаться только в одном случае -- если нужно получить всех котов по бизнес кейсу. В остальных -- фильтрация в БД

2022-05-11 19:48 UTC, Arthasasyan commented on kotiki-java/Service/src/main/java/service/solution/CatServiceImpl.java
> +    public ArrayList<Cat> getFriendsCat(int passportCode) {
Нужно использовать интерфейсы вместо конкретных реализаций. Везде, где возможно

2022-05-14 09:25 UTC, Korihr commented
Защитил

2022-05-14 11:59 UTC, Korihr approved these changes

2022-05-14 11:59 UTC, hiemshaze commented on kotiki-java/Service/src/main/java/service/solution/CatServiceImpl.java
> +        new ServiceException("Нет такого владельца");
Лучше сообщения об ошибках писать на английском языке

2022-05-14 13:35 UTC, merged