lab-3
is-tech-y24-2/Danchechek pull request #3
Opened 2022-05-11 12:40 UTC by Danchechek

2022-05-11 19:54 UTC, Arthasasyan requested changes

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/.idea/.gitignore
> +# Default ignored files
Папка .idea не должна находиться в репозитории

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/.idea/.gitignore
> +# Default ignored files
Также папку нужно переименовать в kotiki-java, это принципиально для инфраструктуры

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/pom.xml
> +        <groupId>org.example</groupId>
Группа должна содержать доменное имя и имя проекта: https://maven.apache.org/guides/mini/guide-naming-conventions.html

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/src/main/java/app/controller/CatController.java
> +    @GetMapping("/allcats")
Получается тавтология

GET /cats/allcats

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/src/main/java/app/controller/CatController.java
> +                return ResponseEntity.badRequest().body("сохранил)");
При соханении стоит возвращать сохраненную сещность, чтобы клиент знал, какой был проставлен id

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/src/main/java/app/entity/CatEntity.java
> +package app.entity;
Пакеты

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/src/main/java/app/entity/CatEntity.java
> +@Table(name = "cats3")
Странное название

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/src/main/java/app/repository/OwnerRepository.java
> +@EntityScan("app.entity.CatEntity")
Такие аннотации можно вешать только на main класс или на Configuration классы

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/src/main/java/app/service/CatService.java
> +        ownerRepository.findAll().forEach(owners::add);
Фильтрацию нужно вынести на уровень БД

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/src/main/java/app/service/CatService.java
> +        ownerRepository.findAll().forEach(owners::add);
Тут достаточно просто проверки на то, что такой пользователь существует. Да и вообще, можно сделать foreign key

2022-05-11 19:54 UTC, Arthasasyan commented on kotiks-spring-java/service/src/main/java/app/service/OwnerService.java
> +public class OwnerService {
Рекомендую сделать интерфейс сервиса и от него сделать реализацию. Это связано с механизмом проксирования спринга. И в принципе является более правильным стилем программирования

2022-05-14 12:55 UTC, Korihr commented
Лаба сдана

2022-05-14 13:35 UTC, merged

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/service/CatServiceImpl.java
> +        List<OwnerEntity> owners = ownerRepository.findAll();
Можно убрать findAll

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/service/CatServiceImpl.java
> +            if ((value.getSecond() == friends.getSecond()
вынести отдельные условия в переменные, для повышения читаемости

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/repository/OwnerRepository.java
> +    OwnerEntity findCatByPassport(@Param("code") int salary);
salary - опечатка

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/OwnerController.java
> +                return ResponseEntity.badRequest().body("null");
Можно заменить на 404

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/CatController.java
> +                return ResponseEntity.ok().body("нет пар");
Можно заменить на 404

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/CatController.java
> +            return ResponseEntity.badRequest().body(catService.getAllCats());
Заменить badRequest() на ok()

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/CatController.java
> +                return ResponseEntity.badRequest().body(catService.findByPassportCat(passport));
Заменить badRequest() на ok()

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/OwnerController.java
> +            return ResponseEntity.badRequest().body("Bad");
В качестве body в случае ошибки можно передавать message или cause исключения

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/CatController.java
> +    public ResponseEntity deleteCat(@RequestBody CatEntity cat) {
Удалять лучше по passportCode, это будет удобней, чем передавать всего кота

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/CatController.java
> +    @PostMapping("/addpair")
Для согласованности, можно заменить addpair на addfriend

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/CatController.java
> +    @GetMapping()
Можно добавить маппинг '/all', а в findByPassportCat наоборот убрать '/bypassport' (по аналогии с findByPassportOwner)

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/controller/OwnerController.java
> +    public ResponseEntity getUsers() {
Можно заменить на getOwners

2022-05-14 13:38 UTC, hiemshaze commented on kotiks-spring-java/service/src/main/java/app/service/CatServiceImpl.java
> +        List<OwnerEntity> owners =  ownerRepository.findAll();
Можно вместо findAll сделать findByPassportCode, и проверять, найдена ли такая сущность. Если нет - то тогда можем сохранять